version: 2
updates:
  - package-ecosystem: cargo
    directory: /apps/api
    schedule:
      interval: weekly
      day: monday
      time: '08:00'
    open-pull-requests-limit: 5
    groups:
      non-major-dependencies:
        update-types:
          - minor
          - patch
    labels:
      - dependencies
      - rust

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '08:00'
    open-pull-requests-limit: 5
    groups:
      non-major-dependencies:
        update-types:
          - minor
          - patch
    labels:
      - dependencies
      - javascript

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    groups:
      non-major-dependencies:
        update-types:
          - minor
          - patch
    labels:
      - dependencies
      - github-actions
