-- Extend timeseries.telemetry with fields from the vehicleState subscription
-- that were not previously captured. All columns nullable.

ALTER TABLE timeseries.telemetry
    ADD COLUMN IF NOT EXISTS charge_port_open        BOOLEAN,
    ADD COLUMN IF NOT EXISTS charger_derate_active   BOOLEAN,
    ADD COLUMN IF NOT EXISTS cabin_precon_status     TEXT,
    ADD COLUMN IF NOT EXISTS cabin_precon_type       TEXT,
    ADD COLUMN IF NOT EXISTS pet_mode_active         BOOLEAN,
    ADD COLUMN IF NOT EXISTS pet_mode_temp_ok        BOOLEAN,
    ADD COLUMN IF NOT EXISTS defrost_active          BOOLEAN,
    ADD COLUMN IF NOT EXISTS steering_wheel_heat     SMALLINT,
    ADD COLUMN IF NOT EXISTS seat_fl_heat            SMALLINT,
    ADD COLUMN IF NOT EXISTS seat_fr_heat            SMALLINT,
    ADD COLUMN IF NOT EXISTS seat_rl_heat            SMALLINT,
    ADD COLUMN IF NOT EXISTS seat_rr_heat            SMALLINT,
    ADD COLUMN IF NOT EXISTS seat_fl_vent            SMALLINT,
    ADD COLUMN IF NOT EXISTS seat_fr_vent            SMALLINT,
    ADD COLUMN IF NOT EXISTS tonneau_locked          BOOLEAN,
    ADD COLUMN IF NOT EXISTS tonneau_closed          BOOLEAN,
    ADD COLUMN IF NOT EXISTS side_bin_left_locked    BOOLEAN,
    ADD COLUMN IF NOT EXISTS side_bin_right_locked   BOOLEAN,
    ADD COLUMN IF NOT EXISTS window_fl_closed        BOOLEAN,
    ADD COLUMN IF NOT EXISTS window_fr_closed        BOOLEAN,
    ADD COLUMN IF NOT EXISTS window_rl_closed        BOOLEAN,
    ADD COLUMN IF NOT EXISTS window_rr_closed        BOOLEAN,
    ADD COLUMN IF NOT EXISTS gear_guard_locked       BOOLEAN,
    ADD COLUMN IF NOT EXISTS gear_guard_video_status TEXT,
    ADD COLUMN IF NOT EXISTS wiper_fluid_low         BOOLEAN,
    ADD COLUMN IF NOT EXISTS brake_fluid_low         BOOLEAN,
    ADD COLUMN IF NOT EXISTS alarm_active            BOOLEAN,
    ADD COLUMN IF NOT EXISTS service_mode            BOOLEAN;
